on : push
jobs :
      first-job :
            rus-on : ubuntu-latest
            steps :
                  - run : node --version
                  - run : npm --version
                  -uses : actions/checkout@v3